######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 26 20:20:06 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += webkit
