######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 26 18:46:48 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
