######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 26 18:09:49 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
